### ISSUE TITLE
Add toy galaxy dataset for training and testing

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/autometacal#3]
To run the various tests we will be interested in, we will need some ready available galaxy images, under a series of noise and PSF conditions. 
This issue is to track the development of a [TensorFlow Dataset](https://www.tensorflow.org/datasets) class that uses GalSim to generate a dataset of postage stamps, with each record having the following entries:
- unsheared/unconvolved galaxy image
- noise statistics 
- PSF

This way, we will be able to add a random shear to the galaxy image on the fly, and add whatever amount of noise we want.

**Comment by EiffL** [comment]
@b-remy can you link here the example of the kappaTNG dataset you implemented?

**Comment by andrevitorelli** [comment]
https://github.com/CosmoStat/jax-lensing/blob/master/jax_lensing/datasets/kappatng.py

**Comment by EiffL** [comment]
Ok, so actually, looks like this issue is becoming redundant with #4 , I'm going to close it and modify the other one
