### ISSUE TITLE
(Small) Code Reestructuring

### ISSUE THREAD

**Issue by andrevitorelli** [CosmoStat/autometacal#30]
Together with issue #28 , I'm trying to reorganise the code so that it becomes more clear. So `datasets` will become `data` (and I intend to, in the future, have a cleanup of that), and we need sub packages for fitting methods (as we will have 3: one taken from ngmix, our simple moments & @b-remy's model fitting). This is mostly renaming and reorganising (except for, again, #28, which I'm doing right now) but I'll then make a PR and ask @EiffL to go through it.

**Comment by EiffL** [comment]
You can open a draft PR, meaning it's not completely ready for review, but it can be convenient.

**Comment by EiffL** [comment]
I think this can be closed? right @andrevitorelli ?

**Comment by andrevitorelli** [comment]
Yes, for now. I'm happy with the current structure (which didn't change much, tbh)
