### ISSUE TITLE
Build a realistic galaxy sample, with some typical SNR, shape, size

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/autometacal#39]
This issue is to track the definition of a fairly realistic galaxy sample we may wish to use for testing. Choices made here are being implemented in #34

**Comment by EiffL** [comment]
So, here is my proposal here: a simple parametric dataset based on CFIS-like conditions:
- pixel size 0.187
- Moffat PSF with FWHM 0.65 arcsec, tiny intrinsic shear
- CFIS depth, i.e. 24 mag  == 10 SNR
- COSMOS 25.2 parametric galaxies
I've implemented a first prototype of this in #40, with an option to include a shear of 0.02 or not. 

Looks like this:
![image](https://user-images.githubusercontent.com/861591/140630097-715a3d84-0b08-4a9f-8e30-bef99bb201c2.png)
![image](https://user-images.githubusercontent.com/861591/140630105-56bbcf94-2b9f-47e3-a55f-6794e67f8ade.png)

@aguinot does that look good to you? As a toy reference galaxy sample? We of course have only 80000 cosmos galaxies but we can augment them as much as we want with random rotations/reflections + different noise realisations.

**Comment by aguinot** [comment]
I think this is reasonable. We may want to cut some galaxies at mag > 24.5 since there are going to be dominated by noise. Regarding the sample size I am not too worry at the moment, I don't see the need for a larger sample given our current experiment. We can think more about that later.
