### ISSUE TITLE
CI via GitHub Action

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/autometacal#8]
Set up stable CI with GalSim on GH Actions

**Comment by EiffL** [comment]
So I took a stab at this and moved to github actions for GalFlow, and apparently it wasn't just a travis thing ^^'
https://github.com/DifferentiableUniverseInitiative/GalFlow/runs/2134845966?check_suite_focus=true
Idon't get it, the exact same code works for python 3.6 and it seems to be working fine for ngmix where I stole this action from https://github.com/esheldon/ngmix/actions

mistery.......... but I guess for now, I'm "happy" with tests running on 3.6 :-/

**Comment by EiffL** [comment]
We need tests ^^' 
The good news is that for galflow tests are running ;-) 
I'm keeping this as an important TODO.
